name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your default branch if different

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run Nightwatch tests
        run: npm test  # Adjust if your test script has a different name

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests run before deploying
    if: success()  # Only deploy if tests pass

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Change to your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build  # Adjust this if your build command is different

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Change this to the directory you want to publish
