name: CI/CD Pipeline🛡️💻🧬

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Security audit
        run: npm audit --audit-level=critical

      - name: Snyk security scan
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          fail-on-issues: false

      - name: Create CodeQL config file
        run: |
          mkdir -p .github/codeql
          echo "language: javascript" >> $GITHUB_WORKSPACE/.github/codeql/codeql-config.yml   

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Run Nightwatch tests
        run: npx nightwatch nightwatch
        continue-on-error: true

      - name: Codecov analysis
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}