name: CI/CD Pipeline🛡️💻🧬

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Security audit
        run: npm audit --audit-level=critical

      - name: Snyk security scan
        uses: snyk/actions@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          fail-on-issues: false

      - name: Create CodeQL config file
        run: |
          mkdir -p .github/codeql
          echo "language: javascript" >> $GITHUB_WORKSPACE/.github/codeql/codeql-config.yml   

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Run Nightwatch tests
        run: npx nightwatch nightwatch
        continue-on-error: true

      - name: Ensure logs directory exists
        run: |
          if [ ! -d "logs" ]; then
            echo "Logs directory does not exist. Creating it..."
            mkdir logs
          else
            echo "Logs directory already exists."
          fi

      - name: Display structure of log files
        if: always()
        run: |
          if [ -d "logs" ]; then
            ls -R logs/
          else
            echo "Logs directory does not exist."
          fi

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Logs
          path: logs/
          retention-days: 1

      - name: Ensure screenshots directory exists
        run: |
          if [ ! -d "screens" ]; then
            echo "Screenshots directory does not exist. Creating it..."
            mkdir screens
          else
            echo "Screenshots directory already exists."
          fi

      - name: Display structure of downloaded files
        if: always()
        run: |
          if [ -d "screens" ]; then
            ls -R screens/
          else
            echo "Screenshots directory does not exist."
          fi

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Screenshots
          path: screens/
          retention-days: 1

      - name: Codecov analysis
        uses: codecov/codecov-action@v1
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}