name: CD -Cloud
on:
  schedule:
    - cron: '0 0 * * *'

jobs: 
  ubuntu-job: 
    name: 'Run tests - browserstack'
    runs-on: ubuntu-latest
    steps: 

      - name: 'Browserstack env setup'
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BS_USERNAME }}
          access-key: ${{ secrets.BS_ACCESS_KEY }}

      - name: 'Nightwatch tests'
        uses: actions/checkout@v2
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm install nightwatch@latest
      - name: Run tests
        run: npm test -- --env browserstack


